### ISSUE TITLE
Super Minify V1.3 crashes my WP site

### ISSUE THREAD

**Issue by wschaepe** [dipakcg/wp-super-minify#1]
When I updated super Minify from V1.2 to V1.3, my WP site crashed. I had to rename the plugin to XXX-BAD and then the site worked.  The site would not  even show- it was a blank screen.  The site is http://www.manhattes.com.  I deleted the plugin

Regards.
Bill Schaepe

**Comment by dipakcg** [comment]
**@wschaepe**, Sorry for the trouble.

I am working on this and should be fixed in the next release.

**Comment by dipakcg** [comment]
**@wschaepe**, Issue has been fixed now. Update your plugin version to 1.3.1 from [WordPress repo.](https://wordpress.org/plugins/wp-super-minify/)

**Comment by wschaepe** [comment]
Thanks !!
